#!/bin/bash
total 16
-rw-r--r-- 1 root root 65 Sep  8 14:52 0-current_working_directory
-rw-r--r-- 1 root root 59 Sep 11 13:20 1-listit
-rw-r--r-- 1 root root 18 Sep 11 14:10 2-bring_me_home
-rw-r--r-- 1 root root  0 Sep 11 14:26 3-listfiles
-rw-r--r-- 1 root root 99 Sep  8 14:39 README.md
